### PR TITLE
Fix is_point_on_curve (fixes issue #48)

### PR DESCRIPTION
**Pull request by olalonde**
See issue #48

### CODE REVIEW

**Comment by antonio-fr** [comment]
I would speed up the whole is_point_on_curve thing :

```
left = pow(y, 2, self.p)
right = pow(x,3,p) + (self.a * x) + self.b
return left == right % self.p
```

**Comment by AntonKueltz** [comment]
Agree with @antonio-fr that we should try to keep `is_point_on_curve` as cheap as possible since it's used whenever a new `Point` is constructed. If possible we should avoid modular square roots.

**Comment by AntonKueltz** [comment]
Based on looking at #48 some more I'm actually leaning towards closing this. Let me know if you agree with my comments in #48, it appears to me the logic is sound and correctly catching an invalid point.

**Comment by AntonKueltz** [comment]
Closing per the last comment left in issue #48. Let me know if you want to discuss further.

**Pull request closed without merging**
